default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  username: postgres
  password: 80688170744

development:
  <<: *default
  database: awesome_ab_development

test:
  <<: *default
  database: awesome_ab_test

production:
  <<: *default
  database: awesome_ab_development